config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts do
      resources :messages, only: :create
    end
  end

  namespace :account do
    resources :groups
    resources :posts
  end

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :posts
  has_many :group_users
  has_many :members, through: :group_users, source: :user
  belongs_to :owner, class_name: 'User', foreign_key: :user_id

  scope :desc_by_posts_count, -> { order('posts_count DESC') }

  validates_presence_of :title, :description

  after_create :join_owner_to_group

  def editable_by?(user)
    user && user == owner
  end

  def join_owner_to_group
    members << owner
  end
end

app/models/group_user.rb
class GroupUser < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :post, dependent: :destroy
  belongs_to :user, dependent: :destroy

  def user_identity
    self.user.try(:name) || 'visitor'
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :group, counter_cache: true
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  has_many :messages

  validates_presence_of :content

  scope :recent, -> { order('updated_at DESC') }

  def editable_by?(user)
    user && user == author
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :groups
  has_many :posts
  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end

  def is_member_of?(group)
    participated_groups.include?(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController
  before_action :login_required

  def index
    @groups = current_user.participated_groups.desc_by_posts_count
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :login_required

  def index
    @posts = current_user.posts.recent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def login_required
    if current_user.blank?
      respond_to do |format|
        format.html { authenticate_user! }
        format.all  { head(:unauthorized) }
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group_by_user, only: %i[edit update destroy]
  before_action :find_group, only: %i[show join quit]

  def index
    @groups = Group.all
  end

  def show
    @posts = @group.posts
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path
  end

  def join
    if current_user.is_member_of?(@group)
      flash[:warning] = 'You are already in the group!'
    else
      current_user.join!(@group)
    end

    redirect_to group_path(@group)
  end

  def quit
    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
    else
      flash[:warning] = 'You are not the member of the group!'
    end

    redirect_to group_path(@group)
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end

  def find_group_by_user
    @group = current_user.groups.find(params[:id])
  end

  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_post

  def create
    @message = @post.messages.new(message_params)
    @message.user = current_user
    @message.save
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[edit update destroy]
  before_action :find_group
  before_action :authenticate_user!, except: [:show]
  before_action :member_required, only: %i[new create]

  def new
    @post = @group.posts.build
  end

  def edit
  end

  def show
    @post = @group.posts.includes(:messages).find(params[:id])
    @messages = @post.messages
    @message = Message.new
  end

  def update
    if @post.update(post_params)
      redirect_to group_path(@group)
    else
      render :edit
    end
  end

  def create
    @post = @group.posts.new(post_params)
    @post.author = current_user

    if @post.save
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to group_path(@group)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def find_post
    @post = current_user.posts.find(params[:id])
  end

  def find_group
    @group = Group.find(params[:group_id])
  end

  def member_required
    unless current_user.is_member_of?(@group)
      flash[:warning] = 'You are not member of this group!'
      redirect_to group_path(@group)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_model_created_at(model)
    model.created_at.strftime('%F %H:%M')
  end

  def render_model_content(model)
    truncate(simple_format(model.content), lenth: 100)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def render_post_updated_at(post)
    post.updated_at.to_s(:long)
  end
end

app/views/groups/_form.html.erb
<div class="container">
  <div class="row">
    <%= simple_form_for @group do |f| %>
      <div class="col-sm-12">
        <%= f.input :title %>
        <%= f.input :description %>
      </div>
      <div class="col-sm-10">
        <%= f.button :submit, class: 'btn-primary' %>
      </div>
      <div class="col-sm-2">
        <%= link_to('Back To Home', groups_path) %>
      </div>
    <% end %>
  </div>
</div>

app/views/groups/edit.html.erb
<%= render 'form' %>

app/views/groups/index.html.erb
<div class="container">
  <div class="col-md-12">
    <div class="group">
      <%= link_to("New Group", new_group_path, class: "btn btn-sm btn-primary pull-right") if current_user %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <thead>
          <tr>
            <th>No.</th>
            <th>Title</th>
            <th>Description</th>
            <th>Options</th>
            <th>Owner</th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= group.id %></td>
              <td><%= link_to(group.title, group_path(group)) %></td>
              <td><%= group.description %></td>
              <td><%= group.owner.name %></td>
              <td>
                <% if current_user && group.editable_by?(current_user) %>
                  <%= link_to('edit', edit_group_path(group), class: "btn btn-default btn-sm", role: 'button') %>
                  <%= link_to('delete', group_path(group), class: "btn btn-default btn-sm", method: :delete, data: { confirm: "Are you sure?" }) %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'form' %>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <% if current_user %>
      <%= link_to('Edit Group Info', edit_group_path(@group), class: "btn btn-mini") if @group.editable_by?(current_user) %>
      <% if current_user.is_member_of?(@group) %>
        <%= link_to("New Post", new_group_post_path(@group), class: "btn btn-sm btn-primary") %>
        <%= link_to("Quit Group", quit_group_path(@group), method: :post, class: "btn btn-sm") %>
      <% else %>
        <%= link_to("Join Group", join_group_path(@group), method: :post, class: "btn btn-sm") %>
      <% end %>
    <% end %>
    <h3><%= @group.title %></h3>
    <p><%= @group.description %></p>
  </div>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-sm-12">
        <div class="col-sm-2"><%= post.author.name %></div>
        <div class="<%= current_user && post.editable_by?(current_user) ? 'col-sm-6' : 'col-sm-10' %>">
          <%= link_to(render_model_content(post), group_post_path(@group, post)) %>
        </div>
        <% if current_user && post.editable_by?(current_user) %>
          <div class="col-sm-4">
            <%= link_to('Edit', edit_group_post_path(post.group, post), class: "btn btn-mini")%>
            <%= link_to('delete', group_post_path(post.group, post), class: "btn btn-default btn-sm", method: :delete, data: { confirm: "Are you sure?" }) %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails101</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="header">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li><%= link_to("Home Family", root_path) %></li>
        <% if current_user.blank? %>
          <li><%= link_to("Sign Up", new_user_registration_path) %></li>
          <li><%= link_to("Log In", new_user_session_path) %></li>
        <% else %>
          <li><%= link_to("My Groups", account_groups_path) %></li>
          <li><%= link_to("My Posts", account_posts_path) %></li>
          <li><%= link_to("Sign Out", destroy_user_session_path, method: :delete) %></li>
        <% end %>
      </ul>
    </nav>
    <h3 class="text-muted">Rails 101</h3>
  </div>

  <div class="row">
    <div class="container">
      <%= yield %>
    </div>
  </div>

  <footer class="footer">
    <p>&copy; Greg 2019</p>
  </footer>
</div>

</body>
</html>

app/views/messages/_message.html.erb
<div class="panel panel-default">
  <p class="panel-heading">
    #
    <%= message.id %>
    <%= message.user_identity %>
    於
    <%= render_model_created_at(message) %>
  </p>
  <p class="panel-body">
    <%= message.content %>
  </p>
</div>

app/views/messages/create.js.erb
<% if @message.valid? %>
  $("#message-list").append("<%=j render partial: "message", locals: { message: @message } %>");
  $("#message_content").val("")
<% else %>
  alert("新增message失敗");
<% end %>

app/views/posts/_form.html.erb
<h3>Group Title: <%= @group.title %> </h3>
<%= simple_form_for [@group,@post] do |f| %>
  <%= f.input :content, input_html: { class: "input-xxlarge" } %>
  <div class="form-actions">
    <%= f.submit "Submit", disable_with: 'Submiting...', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="post">
      <h3>Post</h3>
      <p class="post-content"><%= @post.content %></p>
      <p>
        Create by:
        <%= @post.author.name %>
        --
        <%= render_model_created_at(@post) %>
      </p>
    </div>

    <h3>Comments</h3>
    <div id="message-list">
      <% @messages.each do |message| %>
        <%= render('messages/message', message: message) %>
      <% end %>
    </div>

    <div class="comment-board">
      <%= simple_form_for [@group, @post, @message], remote: true do |f| %>
        <div class="form-group">
          <%= f.input :content, label: 'Comment Board', class: "form-control" %>
        </div>
        <div class="form-actions">
          <%= f.submit "Submit", class: 'btn btn-primary pull-right', disable_with: 'Submitting...' %>
        </div>
      <% end %>
    </div>
  </div>
</div>